import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './globals.css';
import WhatsappButton from '@/components/common/WhatsappButton';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        {children}
        <WhatsappButton />
      </body>
    </html>
  );
}
