console.log('🧹 Código para limpiar el caché del navegador:');
console.log('');
console.log('// Copia y pega esto en la consola del navegador:');
console.log('');
console.log('// Limpiar localStorage');
console.log('localStorage.clear();');
console.log('');
console.log('// Limpiar sessionStorage');
console.log('sessionStorage.clear();');
console.log('');
console.log('// Limpiar todas las cookies');
console.log('document.cookie.split(";").forEach(function(c) {');
console.log('  document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/");');
console.log('});');
console.log('');
console.log('// Limpiar caché del navegador (Ctrl+Shift+R)');
console.log('// O ejecutar:');
console.log('window.location.reload(true);');
console.log('');
console.log('// Después intenta acceder a: http://localhost:3000/admin');
